import './globals.css'

export const metadata = {
  title: 'Dg Vaishnav College',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-[100%] w-full">
        {children}
      </body>
    </html>
  )
}
