import Footer from "@/components/footer";
import "./globals.css";
import { Urbanist } from "next/font/google"
import Navbar from "@/components/header/navbar";

const urbanist = Urbanist({ subsets: ["latin"], variable: "--Urbanist", weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata = {
  title: "Dg Vaishnav College",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${urbanist.variable} font-Urbanist`}>
        <div className="w-full h-screen">
          {/* Navbar */}
          <Navbar />

          {/* Content */}
          {children}

          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
