import Footer from "@/components/footer";
import "./globals.css";
import { Poppins } from "next/font/google"

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--poppins",
  preload: true,
  subsets: ["latin"]
});

export const metadata = {
  title: "Dg Vaishnav College",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-Poppins`}>
        <div className="w-full h-screen">
          {/* Header */}

          {/* Content */}
          {children}

          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
